### ISSUE TITLE
Add French Translation

### ISSUE THREAD

**Issue by Xin4rius** [thehallowedfire/ModernCharacterFrame#1]
Hey,

I have created a french translation for this addon, It would be convenient to increase the number of users. How can I give add it in the project ?

**Comment by thehallowedfire** [comment]
Hi. I'm very new on GitHub, but if I understood correct, ideally you need to create a fork, then edit it (eg. by adding another file) and then request pull by choosing your fork. But I'm not sure.
To make it simplier you could just post your code or frFR.lua file here. I'll add it manually.
I also have plans to add some more locale strings, so if it's ok I'll write to you again later, so you could translate new strings as well.

**Comment by thehallowedfire** [comment]
And don't you mind if I mention your name as author of french localization (on CurseForge)?

**Comment by thehallowedfire** [comment]
I updated localization file structure a little bit. You can use enUS.lua as a template.

**Comment by thehallowedfire** [comment]
I believe I created new branch for you. Try to edit it. You can also edit it in browser: open your branch and press "." (dot key). It will open VS Code right in browser. Then you can copy enUS file and edit it (actually you need to use " if GetLocale() == "frFR" " thing like in ruRU.lua but I can add it myself when you ready).

**Comment by Xin4rius** [comment]
I have made a pull request #2  with the new files (frFR.lua and update of ModernCharacterFrame.toc), I wrote my character name and the server in the variable L["MCF_OPTIONS_DESCRIPTION"] like you. If you want to credit me on cursedforge you can with my character name (Datyb). If you want contact me, add me on discord at Alban / Xin4rius#0001 !

**Comment by thehallowedfire** [comment]
Hey. I merged your translation into master branch. Also uploaded new v0.5.4 release on GitHub and CurseForge (it's still under review, should be avaliable soon).
I changed a little bit frFR.lua file to make the same structure as in enUS/ruRU locales. If you can, translate please also this line (check comment): https://github.com/thehallowedfire/ModernCharacterFrame/blob/d63b351b20699ade604e7a51b7ba124b07394d2f/Localization/frFR.lua#L19-L20

And thank you for contributing!

**Comment by Xin4rius** [comment]
Alright, I did the modification ! #4

**Comment by thehallowedfire** [comment]
Thank you! Merged with master branch. You can download latest version from GitHub code (but it will contain a few unused files which I always delete from release's .zip) or just wait until next release and update from CurseForge app.
